export const ErrorCodes = {
  BAD_REQUEST: { code: 40000, message: '请求参数不合法' },
  UNAUTHORIZED: { code: 40100, message: '未登录' },
  TOKEN_EXPIRED: { code: 40101, message: 'Token 已过期' },
  INVALID_TOKEN: { code: 40102, message: '无效 Token' },
  FORBIDDEN: { code: 40300, message: '权限不足' },
  ROLE_REQUIRED: { code: 40301, message: '需要特定角色' },
  NOT_FOUND: { code: 40400, message: '资源不存在' },
  USER_NOT_FOUND: { code: 40401, message: '用户不存在' },
  ROLE_NOT_FOUND: { code: 40402, message: '角色不存在' },
  CONFLICT: { code: 40900, message: '资源冲突' },
  USERNAME_EXISTS: { code: 40901, message: '用户名已存在' },
  EMAIL_EXISTS: { code: 40902, message: '邮箱已存在' },
  ROLE_CODE_EXISTS: { code: 40903, message: '角色编码已存在' },
  VALIDATION_ERROR: { code: 42200, message: '参数验证失败' },
  RATE_LIMITED: { code: 42900, message: '请求过于频繁' },
  INTERNAL_ERROR: { code: 50000, message: '服务器内部错误' },
  AI_ERROR: { code: 50001, message: 'AI 服务异常' },
  DB_ERROR: { code: 50002, message: '数据库异常' },
} as const
